# Generated by Django 5.2.6 on 2025-09-09 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AD_JUDICIA', 'Ad Judicia')], default='AD_JUDICIA', max_length=50, verbose_name='Tipo de Procuração')),
                ('outorgante', models.CharField(max_length=200, verbose_name='Outorgante')),
                ('outorgado', models.CharField(max_length=200, verbose_name='Outorgado')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('esta_vencida', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procuração',
                'verbose_name_plural': 'Procurações',
            },
        ),
    ]
