# Generated by Django 5.2.6 on 2025-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procuracao',
            name='esta_vencida',
        ),
        migrations.AddField(
            model_name='procuracao',
            name='numero',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Número da Procuração'),
        ),
        migrations.AddField(
            model_name='procuracao',
            name='prioridade',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='procuracao',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('renewed', 'Renovada')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
